# Generated by Django 6.0.6 on 2026-07-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Company Owner'), ('FINANCE_MANAGER', 'Finance Manager'), ('OPERATIONS_MANAGER', 'Operations Manager'), ('ACCOUNTANT', 'Accountant'), ('VIEWER', 'Viewer / Auditor')], default='VIEWER', max_length=30),
        ),
    ]
