# Generated by Django 6.0.6 on 2026-07-01 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='companies.company'),
        ),
    ]
