# Generated by Django 6.0.6 on 2026-07-03 06:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('GOODS', 'Goods'), ('LOGISTICS', 'Logistics'), ('TARIFFS', 'Tariffs'), ('SERVICES', 'Services'), ('OTHER', 'Other')], max_length=30)),
                ('country', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100, unique=True)),
                ('transaction_volume', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('VERIFIED', 'Verified'), ('PENDING_KYC', 'Pending KYC'), ('SYSTEM', 'System'), ('INACTIVE', 'Inactive')], default='PENDING_KYC', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
