# Generated by Django 6.0.6 on 2026-07-04 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
