# Generated by Django 6.0.6 on 2026-07-20 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_purchaseorder_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='account_number',
        ),
    ]
