# Generated by Django 6.0.6 on 2026-07-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_remove_supplier_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
