# Generated by Django 6.0.6 on 2026-07-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_supplier_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
