# Generated by Django 6.0.6 on 2026-07-08 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_purchaseorder_notes'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualaccount',
            name='account_holder_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='virtualaccount',
            name='account_reference',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='virtualaccount',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='virtualaccount',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='virtual_accounts', to='companies.company'),
        ),
        migrations.AddField(
            model_name='virtualaccount',
            name='currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
        migrations.AddField(
            model_name='virtualaccount',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualaccount',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='virtualaccount',
            name='raw_response',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='virtualaccount',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_accounts', to='companies.supplier'),
        ),
    ]
