# Generated by Django 6.0.6 on 2026-07-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_virtualaccount_account_holder_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualaccount',
            name='provider_account_id',
        ),
    ]
