# Generated by Django 6.0.6 on 2026-07-20 11:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_purchaseorder_notes'),
        ('payments', '0003_remove_virtualaccount_provider_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualaccount',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='virtualaccount',
            name='provider',
            field=models.CharField(default='MONNIFY', max_length=30),
        ),
        migrations.CreateModel(
            name='MonnifyCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key', models.CharField(max_length=255)),
                ('secret_key', models.CharField(max_length=255)),
                ('contract_code', models.CharField(max_length=100)),
                ('environment', models.CharField(default='sandbox', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monnify_credentials', to='companies.company')),
            ],
        ),
        migrations.DeleteModel(
            name='NombaCredential',
        ),
    ]
