# Generated by Django 6.0.6 on 2026-07-20 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_remove_supplier_account_number'),
        ('payments', '0004_virtualaccount_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualaccount',
            name='supplier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_account', to='companies.supplier'),
        ),
    ]
