# Generated by Django 6.0.6 on 2026-07-21 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_virtualaccount_supplier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settlement',
            name='virtual_account',
        ),
        migrations.AddField(
            model_name='settlement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_settlements', to=settings.AUTH_USER_MODEL),
        ),
    ]
