# Generated by Django 6.0.6 on 2026-07-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_settlement_virtual_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='raw_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
