# Generated by Django 6.0.6 on 2026-07-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_settlement_transaction_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
