/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVirtualAccountsRouteImport } from './routes/app.virtual-accounts'
import { Route as AppSuppliersRouteImport } from './routes/app.suppliers'
import { Route as AppSubscriptionsRouteImport } from './routes/app.subscriptions'
import { Route as AppSettlementsRouteImport } from './routes/app.settlements'
import { Route as AppPurchaseOrdersRouteImport } from './routes/app.purchase-orders'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVirtualAccountsRoute = AppVirtualAccountsRouteImport.update({
  id: '/virtual-accounts',
  path: '/virtual-accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppSubscriptionsRoute = AppSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AppRoute,
} as any)
const AppSettlementsRoute = AppSettlementsRouteImport.update({
  id: '/settlements',
  path: '/settlements',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersRoute = AppPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/docs': typeof DocsRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/settlements': typeof AppSettlementsRoute
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/virtual-accounts': typeof AppVirtualAccountsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/settlements': typeof AppSettlementsRoute
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/virtual-accounts': typeof AppVirtualAccountsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/docs': typeof DocsRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/settlements': typeof AppSettlementsRoute
  '/app/subscriptions': typeof AppSubscriptionsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/virtual-accounts': typeof AppVirtualAccountsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/docs'
    | '/app/purchase-orders'
    | '/app/settlements'
    | '/app/subscriptions'
    | '/app/suppliers'
    | '/app/virtual-accounts'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/app/purchase-orders'
    | '/app/settlements'
    | '/app/subscriptions'
    | '/app/suppliers'
    | '/app/virtual-accounts'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/docs'
    | '/app/purchase-orders'
    | '/app/settlements'
    | '/app/subscriptions'
    | '/app/suppliers'
    | '/app/virtual-accounts'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DocsRoute: typeof DocsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/virtual-accounts': {
      id: '/app/virtual-accounts'
      path: '/virtual-accounts'
      fullPath: '/app/virtual-accounts'
      preLoaderRoute: typeof AppVirtualAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/subscriptions': {
      id: '/app/subscriptions'
      path: '/subscriptions'
      fullPath: '/app/subscriptions'
      preLoaderRoute: typeof AppSubscriptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settlements': {
      id: '/app/settlements'
      path: '/settlements'
      fullPath: '/app/settlements'
      preLoaderRoute: typeof AppSettlementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchase-orders': {
      id: '/app/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/app/purchase-orders'
      preLoaderRoute: typeof AppPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppPurchaseOrdersRoute: typeof AppPurchaseOrdersRoute
  AppSettlementsRoute: typeof AppSettlementsRoute
  AppSubscriptionsRoute: typeof AppSubscriptionsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppVirtualAccountsRoute: typeof AppVirtualAccountsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppPurchaseOrdersRoute: AppPurchaseOrdersRoute,
  AppSettlementsRoute: AppSettlementsRoute,
  AppSubscriptionsRoute: AppSubscriptionsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppVirtualAccountsRoute: AppVirtualAccountsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DocsRoute: DocsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
